### ISSUE TITLE
credentials api is not descriptive

### ISSUE THREAD

**Issue by mjudeikis** [jim-minter/rp#11]
Suggestion to be add 
```
	out := &OpenShiftClusterCredentials{
		KubeadminPassword: oc.Properties.KubeadminPassword,
		KubeadminUsername: oc.Properties.KubeadminUsername,
	}
```
to credentials api as it requires product knowledge to know the username. Which is not clear from the response. 

@jim-minter wdyt?

**Comment by jim-minter** [comment]
open to doing this but want to delay until the next round of API/schema changes
