### ISSUE TITLE
[story]Cloud-Credentials

### ISSUE THREAD

**Issue by mjudeikis** [jim-minter/rp#22]
When this https://github.com/openshift/cloud-credential-operator/pull/142 merges we will need to change the flow of how credentials are used.

1. Move from shared team secret to individual secret
2. Certificates are generated as per readme.md and added to the vault
3. The certificate has to be added to the aad application (manual step) 
4. 2 RG has to be provided by end-user (VNET and main cluster one). 
       Need to verify if we can create cluster one with main credentials. RP fails to deploy cluster if AAD app does not have contributor rights on BOTH groups.

**Comment by mjudeikis** [comment]
AAD user must be Owner on VNET group as it needs to manager Roles:
```
AuthorizationFailed" Message="The client '87073447-485f-422a-bc90-7fa438c374e6' with object id '87073447-485f-422a-bc90-7fa438c374e6' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/mjudeikis-cco-pass-vnet/providers/Microsoft.Network/virtualNetworks/mjudeikis-cco-pass-vnet/providers/Microsoft.Authorization/roleAssignments/c1081e4e-5eb0-4fe5-a20d-310683403115
```

**Comment by jim-minter** [comment]
I never really understood what this issue was about, not transferring it to the new repo.
