### ISSUE TITLE
make delete non-blocking

### ISSUE THREAD

**Issue by mjudeikis** [jim-minter/rp#57]
Scenario: I started a cluster creation for tests. My parallel tests failed, and de-provisioning started.
Because the cluster is in `Creating` state I cant submit Delete call and have to wait until it completes or fails.

I should be able to submit delete call at any point in time and cancel all previous operations running.

@jim-minter wdyt?

**Comment by mjudeikis** [comment]
``` 	// Provisioning state machine:
	//
	// From ARM's perspective, Succeeded and Failed are the only two terminal
	// provisioning states for asynchronous operations.  Clients will poll PUT,
	// PATCH or DELETE operations until the resource gets to one of those
	// provisioning states.
	//
	// ARO uses Creating, Updating and Deleting as non-terminal provisioning
	// states to signal asynchronous operations from the front end to the back
	// end.
	//
	// In case of failures, the back end sets failedProvisioningState to the
	// provisioning state at the time of the failure.
	//
	// The ARO front end gates provisioning state machine transitions as
	// follows:
	//
	// * no PUT, PATCH or DELETE is accepted unless the cluster is currently in
	//   a terminal provisioning state.
	//
	// * DELETE is always allowed regardless of the terminal provisioning state
	//   of the cluster.
	//
	// * PUT and PATCH are allowed as long as the cluster is in Succeeded
	//   provisioning state, or in a Failed provisioning state with the failed
	//   provisioning state to Updating.
	//
	// i.e. if a cluster creation or deletion fails, there is no remedy but to
	// delete the cluster.
```

based on this should be a case, but it is not currently. before fixing wanted to confirm 
Or im missuderstanding all this ` * DELETE is always allowed regardless of the terminal provisioning state of the cluster`

**Comment by mjudeikis** [comment]
``` 
[mjudeiki@unknown rp]$ az aro delete -g mjudeikis-test1 -n mjudeikis-test1-cluster 
Request is not allowed in provisioningState 'Creating'.```

**Comment by jim-minter** [comment]
I agree with the goal; this is a multi-step work item.  The more important driver here is actually to allow a backend that realises that it's lost a record lease due to a network glitch to cancel the work it's doing.

First step is to make the context that the backend worker use cancelable, and have the heartbeat code control that context so that if it realises it loses the lease, it cancels the context.

Following on from that we can think about how to cancel the context and wait for cleanup in the case of an early delete.

**Comment by mjudeikis** [comment]
Agree, this is why I raised this as I want to flush down the requirements as I think it is a big item:
1. Heartbeat cancels the backend workers to stop working on a document.
2. Frontend needs to be able to notify the document/ cluster with the change of "desirable state". In example: Create would mark the document as  Desired state: Running`. So backend would continue with work until it reaches this state.
If frontend receives interrupt, like Delete. It updates the document `Desired state: Deleted`.
If the heartbeat routine detects a change in the desired state, it cancels the worker, changes the document to be deleted, and releases the document to be re-queued by another worker for deletion. 

Any thoughts?

**Comment by jim-minter** [comment]
Yes, something like that, but using provisioningState Creating and Deleting.  I think the release/requeue part is redundant.
